name: publish nuget

on:
  push:
    branches: [ main ]

jobs:
  Publish-NuGet-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Git fetch unshallow
      run: git fetch --prune --unshallow
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.3.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v4.1.0
      with:
        configFilePath: .github/GitVersion.yml
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --no-restore
    - name: Push
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.API_KEY }} --source https://api.nuget.org/v3/index.json
